---
title: "Precision"  
output: html_document
date: "2025-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE)
library(ospsuite.reportingframework)
library(data.table)

setDefaults()
```

```{r inputList}

generationFunctionList = list(
  list(generationFunction = 'rnorm',
       par = list(mean=1,sd = 0.2),
       scale = 'linear'),
  list(generationFunction = 'rnorm',
       par = list(mean=1,sd = 0.1),
       scale = 'linear'),
  list(generationFunction = 'rnorm',
       par = list(mean=1,sd = 0.05),
       scale = 'linear'),
  list(generationFunction = 'rlnorm',
       par = list(meanlog = log(1),sdlog = log(1.1)),
       scale = 'log'),
  list(generationFunction = 'rlnorm',
       par = list(meanlog = log(1),sdlog = log(1.4)),
       scale = 'log'),
  list(generationFunction = 'rlnorm',
       par = list(meanlog = log(1),sdlog = log(2.5)),
       scale = 'log')
)

generationFunctionList = list(
  list(generationFunction = 'rnorm',
       sd = 0.2,
       scale = 'linear'),
  list(generationFunction = 'rnorm',
       sd = 0.1,
       scale = 'linear'),
  list(generationFunction = 'rnorm',
       sd = 0.05,
       scale = 'linear')
)




aggregationFunctionList <- list(c(mean = mean),
     c(geomean = geomean),
     c(median = median),
     c(q5 = function(y){quantile(y,probs = 0.05)}))


maxN = 10000
precisionThreshold <- 0.01
meanValue = 1


```

```{r samplecreation}

myValues = data.table()

for (g in generationFunctionList){

    values <- rnorm(n = maxN,mean = meanValue,sd = g$sd)
  
    gDisplayName = paste0('mean = ', meanValue, 
                          '; sd = ', g$sd)
    
    myValues = rbind(myValues,
                     data.table(values = values,
                                generationFunction = 'normal',
                                gDisplayName = gDisplayName,
                                variance = g$sd))
    
    valuesL <- exp(values-meanValue)*meanValue
    
    gDisplayName = paste0('geomean = ', round(geomean(valuesL)), 
                      '; geosd = ', round(geosd(valuesL),2))
    
    
    myValues = rbind(myValues,
                     data.table(values = valuesL,
                                generationFunction = 'lognormal',
                                gDisplayName = gDisplayName,
                                variance = round(geosd(valuesL),2)))

}

```

```{r plotHist}

  p1 <- 
    ggplot(myValues[generationFunction == 'normal' ]) +
    geom_histogram(aes(values),bins = 30) +
      facet_wrap(vars(gDisplayName))
  p2 <- 
    ggplot(myValues[generationFunction == 'lognormal' ]) +
    geom_histogram(aes(values),bins = 30) +
      facet_wrap(vars(gDisplayName)) +
    scale_x_log10() 
  
   print(cowplot::plot_grid(p1,p2,ncol = 1))
   


```

```{r datacreation}
myDT = data.table()

for (gName in unique(myValues$gDisplayName)){
  
  tmpValues = myValues[gDisplayName == gName]

  for (N in round(10^(seq(2,log10(maxN),1/4)))){

    for (aggregationFun in aggregationFunctionList){

      tmp <- calculateAggregationWithCIBYGroup(
        dt = data.table(scenario = paste0('N',N),
                        value = tmpValues$values[1:N]),
        aggregationFun = aggregationFun,
        identifier = 'scenario')
      
      tmp[,IQR := IQR(tmpValues$values[1:N])]
      tmp[,generationFunction := tmpValues$generationFunction[1]]
      tmp[,aggregationFun := names(aggregationFun)]
      tmp[,gDisplayName := gName]
      tmp[,variance := tmpValues$variance[1]]

      myDT = rbind(myDT,tmp)

    }
  }
}

myDT[,precision := (yMax-yMin)/yValues]


```



```{r confidenceinterval}

ggplot(myDT,
       mapping = aes(
         x = yValues,
         xmin = yMin,
         xmax = yMax,
         y = as.factor(variance),
         color = as.factor(N)
       )) +
  geom_point(position = position_dodge(width = 1)) +
  geom_errorbar(position = position_dodge(width = 1)) +
  facet_wrap(
    vars(generationFunction, aggregationFun),
    scales = 'free',
    ncol = dplyr::n_distinct(myDT$aggregationFun)
  ) +
  labs(y = '(sd or gsd)',
       x = '',
       color = 'N') +
  theme(legend.position = 'top',legend.direction = 'horizontal')

```


```{r interp}

myDT[, intersectionN := 
       exp(approx(x = log(sqrt(precision)),y = log(N), xout = log(sqrt(precisionThreshold)))$y),
     by = .(aggregationFun, gDisplayName)]

ggplot(myDT,
       mapping = aes(
         x = N,
         y = sqrt(precision),
         color = as.factor(variance)
       )) +
  geom_point() +
  geom_line() +
  facet_wrap(
    vars(generationFunction, aggregationFun, ),
    #scales = 'free',
    ncol = dplyr::n_distinct(myDT$aggregationFun)
  ) +
  labs(color = 'sd or gsd') +
  theme(legend.position = 'top',legend.direction = 'horizontal') +
    scale_x_log10() +
  scale_y_log10() +
  geom_hline(yintercept = sqrt(precisionThreshold)) +
  geom_vline(mapping = aes(xintercept = intersectionN,color = as.factor(variance)))

```

```{r}
if (!('IQR' %in% names(myDT))){
  myDT <- merge(myDT,
                myValues[,.(IQR =IQR(values)),by = 'gDisplayName'],
                by = 'gDisplayName')
}

ggplot(myDT,
       mapping = aes(
         x = IQR,
         y = intersectionN,
         color = as.factor(variance)
       )) +
  geom_point() +
  # facet_wrap(
  #   vars(generationFunction, aggregationFun, ),
  #   #scales = 'free',
  #   ncol = dplyr::n_distinct(myDT$aggregationFun)
  # ) +
  labs(color = 'sd or gsd') +
  theme(legend.position = 'top',legend.direction = 'horizontal') 


```


```{r}
tmp = myDT[aggregationFun == 'mean' & generationFunction == 'normal' & variance == 0.2]


ggplot(tmp, mapping = aes(x = log(N^2), y = log(precision^2))) +
  geom_point() 

  geom_smooth(method = 'lm')


lm(log(N) ~ log(precision),data = tmp)
```


```{r}
# Z-score for the desired confidence level
zScore <- qnorm(1 - (1 - 0.9) / 2)

# Calculate required sample size
myDT[,requiredSampleSize := ((zScore*IQR*1.5)/(yValues*precisionThreshold))^2]

```


```{r}
ggplot(myDT,
       mapping = aes(
         x = N,
         y = requiredSampleSize/intersectionN,
         fill = as.factor(variance)
       )) +
  geom_point() +
  facet_wrap(
    vars(generationFunction, aggregationFun),
    ncol = dplyr::n_distinct(myDT$aggregationFun)
  ) +
  geom_hline(yintercept = 1) +
  labs(fill = 'sd or gsd',
       y = 'N estimated/ N interpolation') +
  theme(legend.position = 'top',legend.direction = 'horizontal') +
  scale_y_log10() +
  scale_x_log10(limits = range(myDT$N)) 

```



```{r}
ggplot(myDT,
       mapping = aes(
         x = N,
         y =  log(precision/IQR)/N),
         fill = as.factor(variance)
       )) +
  geom_point() +
  facet_wrap(
    vars(generationFunction, aggregationFun),
    ncol = dplyr::n_distinct(myDT$aggregationFun)
  ) +
  labs(fill = 'sd or gsd') +
  theme(legend.position = 'top',legend.direction = 'horizontal') +
  #scale_y_log10() +
  scale_x_log10()
```


