---
title: "Workflow for Report generation"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
```

```{r libraries-copy}
library(ospsuite.reportingframework)
```

```{r loadResults-copy}
scenarioList <-
  createScenarios.wrapped(projectConfiguration = projectConfiguration,
                          scenarioNames = scenarioNames)

# It is assumed that all required scenarios were simulated in previous workflow started in same project directory.
scenarioResults <- loadScenarioResults(projectConfiguration = projectConfiguration,
                                       scenarioList = scenarioList)

pkParameterDT <- loadPKParameter(projectConfiguration = projectConfiguration,
                                 scenarioList = scenarioList)
```

```{r runPlot-copy}
# set graphic
ospsuite.plots::setDefaults()
theme_update(legend.position = 'top')
options(knitr.kable.NA = '')

# timeprofiles
runPlot(
  nameOfplotFunction = "plotTimeProfiles",
  projectConfiguration = projectConfiguration,
  inputs = list(
    configTableSheet = "TimeProfiles",
    dataObserved = dataObserved,
    scenarioResults = scenarioResults
  )
)
```

```{r customfunctions-replace}
if (length(pathsCustomfunctions) > 0)
  lapply(pathsCustomfunctions,source)
```

```{r workflowOptions-replace}
qCpassed <- suppressWarnings(as.logical(as.double(Sys.getenv(x='QCpassed',unset = 0))))
# check if QCpassed was set as "TRUE" or "FALSE"
if (is.na(qCpassed))   qCpassed <- as.logical(Sys.getenv(x='QCpassed',unset = 0))
if (is.na(qCpassed)) stop("Environment Variable 'QCpassed' is not a logical")

setWorkflowOptions(isValidRun = qCpassed)
```

```{r projectConfiguration-replace}
projectConfiguration <-
  ospsuite.reportingframework::createProjectConfiguration(
    path =  file.path("ProjectConfiguration.xlsx"))

initLogfunction(projectConfiguration)
```

```{r finalize-replace}
addMessageToLog("finalize workflow")

# save Session Infos including the loaded packages and R version, into a log file
saveSessionInfo()
```

```{r customfunctions-eval}
pathsCustomfunctions <- c()
```

```{r observedTimeprofiles-eval}
# use this line if you have no observed time profile data
dataObserved <- NULL

# use code below if you have observed time profile data
dataObserved <- readObservedDataByDictionary(projectConfiguration = projectConfiguration,
                                             dataClassType = 'timeprofile',
                                             fileIds = NULL)

# here you can add your own code to manipulate and clean the data if necessary
```

```{r observedPKParameter-eval}
# use this line if you have no observed pk-Parameter data
dataObservedPK <- NULL

# use code below you have observed pk-Parameter data
dataObservedPK <- readObservedDataByDictionary(projectConfiguration = projectConfiguration,
                                             dataClassType = 'pkParameter',
                                             fileIds = NULL)
# here you can add your own code to manipulate and clean the data if necessary
```

```{r loadResults-eval}
scenarioNames = c()
```
