#' @param observedData either `data.table` which was generated by \code{\link{readDataByDictionary}} or object of class `DataCombined`,
#' which will internally transfer to the data.table format by \code{\link{convertDataCombinedToDataTable}}

