---
title: "Introduction to OSPSuite Reporting Framework"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{OSPSuite_ReportingFramework}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
```

# Introduction

The **OSPSuite Reporting Framework** is a powerful R package designed to streamline the process of data analysis, visualization, and reporting in pharmacokinetic and clinical research contexts. This package offers a comprehensive set of tools that facilitate the import of data, simulation of scenarios, calculation of pharmacokinetic parameters, and generation of insightful visualizations and reports.
The package based on `{esqlabsR}` which facilitates modeling and simulation workflows with the OSPSuite relying on a well defined project structure based on Excel files.
This package is the base for other packages such as Bayesian Multi-Level Model Optimization package `{OSPSuite.BMLM}`

## Key Features

- **Data Import**: Import observed data and pharmacokinetic parameters with ease.
- **Simulation Management**: Set up and run simulations, including the calculation of PK parameters.
- **Plotting Capabilities**: Generate a variety of plots to visualize data and results effectively.
- **Report Generation**: Compile results into well-structured reports for regulatory submissions.

## Available Vignettes

To help you get started and make the most of the OSPSuite Reporting Framework, we provide several vignettes that cover different aspects of the package. Below is a list of available vignettes along with a brief description of each:

1. **[Workflow Setup and Execution](Workflow.html)**: Understand the typical workflow setup and the various components involved in using the framework.

2. **[Data Import by Dictionary](Data_import_by_dictionary.html)**: Learn how to import observed data and PK parameters using a configuration dictionary.

3. **[Population](Population)**: Explore the concepts of random and virtual twin populations within the framework.

4. **[PK Parameters](PK-Parameter)**: Get insights into calculating and visualizing pharmacokinetic parameters across various scenarios.

5. **[Plot and Report Generation](Plot_and_Report_Generation.html)**: Discover how to generate plots and compile them into comprehensive reports.

6. **[Tutorial: Time Profile Plotting](Tutorial-timeprofiles.html)**: Follow a step-by-step guide to generating time profile plots using the package.

7. **[Electronic Package](Electronic-Package.html)**: Understand how to create a structured electronic package for regulatory submissions.

Explore the vignettes to familiarize yourself with the package functionalities and start your journey with the reporting framework!
If you have any feedback or suggestions for improvement, please feel free to reach out!
