# Purpose: Tutorial workflow
#

# Typically This file is saved in <Rootdirectory>\Scripts\ReportingFramework

# set working directory to  workflow file location, (only if working interactively)
if (interactive() && rstudioapi::isAvailable()) {
  # Get the active document path in RStudio
  activeDocPath <- rstudioapi::getActiveDocumentContext()$path
  setwd(dirname(activeDocPath))
}


# Initialization
# load libraries and source project specific code
library(ospsuite.reportingframework)

# set graphic
# (see vignette(package = 'ospsuite.plots',topic = 'ospsuite_plots'))
ospsuite.plots::setDefaults()
theme_update(legend.position = 'top')
options(knitr.kable.NA = '')

# Set this to TRUE if you want to execute the workflow as a final valid run.
# It then won't set watermarks to figures and does not skip failing plot generations
# (see vignette OSPSuite_ReportingFramework)
setWorkflowOptions(isValidRun = FALSE)

# Setup project structure
# creates project directory
# (see help initProject and https://esqlabs.github.io/esqlabsR/articles/esqlabsR.html)
# if you go with the default structure
# this workflow file should be saved in Scripts/ReportingFramework,
initProject()


# get paths of all relevant project files
projectConfiguration <-
  ospsuite.reportingframework::createProjectConfiguration(
    path =  file.path("ProjectConfiguration.xlsx"))

initLogfunction(projectConfiguration)


# 1) Read observedData -------------------------------------------------------
# (see vignette(package = 'ospsuite.reportingframework',topic = 'Data_import_by_dictionary'))

# read data as data.table
dataObserved <- readObservedDataByDictionary(projectConfiguration = projectConfiguration)

# add aggregated  groups of data
dataObserved <- rbind(dataObserved,
                      aggregateObservedDataGroups(
                        dataObserved = dataObserved,
                        groups = c("1234_iv","1234_po")
                      ),
                      fill = TRUE
)
# for the manually added groups the configuration sheet in Plot.xlsx has to be updated
updateDataGroupId(projectConfiguration, dataObserved)

# 2) Export populations -------------------------------------------------------
# (see vignette Simulation_setup)

exportVirtualTwinPopulations(
  projectConfiguration = projectConfiguration,
  populationNames = NULL,
  modelFile = "po 3 mg (solution).pkml",
  overwrite = FALSE
)

exportRandomPopulations(
  projectConfiguration = projectConfiguration,
  populationNames = NULL,
  overwrite = FALSE
)


# 3) Simulations ------------------------------------------------------
# (see  vignette Simulation_setup)
scenarioList <-
  createScenarios.wrapped(
    projectConfiguration = projectConfiguration,
    scenarioNames = NULL
  )

scenarioResults <- runAndSaveScenarios(
  projectConfiguration = projectConfiguration,
  scenarioList = scenarioList,
  simulationRunOptions = SimulationRunOptions$new(
    showProgress = TRUE
  )
)

# 5) Create Output Plots -----------------------------------------------------
# (see vignette OSPSuite_ReportingFramework.Rmd  section  Plot Functionality)

addDefaultConfigForTimeProfilePlots(
  projectConfiguration = projectConfiguration,
  sheetName = "TimeProfiles",
  overwrite = FALSE
)


runPlot(
  nameOfplotFunction = "plotTimeProfiles",
  projectConfiguration = projectConfiguration,
  configTableSheet = "TimeProfiles",
  inputs = list(
    dataObserved = dataObserved,
    scenarioResults = scenarioResults,
    referenceScaleVector = list('1mg iv simulation' = 'grey'),
    xscale.args = list(limits = c(NA,NA))
  )
)

# 6) Create Report document --------------------------------------------------
mergeRmds(
  projectConfiguration = projectConfiguration,
  newName = "TutorialPlots",
  title = "Plots generated by tutorial",
  sourceRmds = c("TimeProfiles")
)

renderWord(fileName = file.path(projectConfiguration$outputFolder, "TutorialPlots.Rmd"))

# finalize workflow---------------------
addMessageToLog("finalize workflow")

# save Session Infos including the loaded packages and R version, into a log file
saveSessionInfo()
