# Purpose: Tutorial workflow
#

# Typically This file is saved in <Rootdirectory>\Scripts\ReportingFramework

# set working directory to  workflow file location, (only if working interactively)
if (interactive() && rstudioapi::isAvailable()) {
  # Get the active document path in RStudio
  activeDocPath <- rstudioapi::getActiveDocumentContext()$path
  setwd(dirname(activeDocPath))
}


# Initialization
# load libraries and source project specific code
library(ospsuite.reportingframework)

# Set graphic defaults
# (see vignette(package = 'ospsuite.plots', topic = 'ospsuite_plots'))
ggplot2::theme_set(theme_osp())
theme_update(legend.position = 'top')
options(knitr.kable.NA = '')

# Set this to TRUE if you want to execute the workflow as a final valid run.
# (see ?setWorkflowOptions)
setWorkflowOptions(isValidRun = FALSE)

# Setup project structure
# This workflow file is saved in Scripts/ReportingFramework (the configurationDirectory).
# initProject() is called with configurationDirectory = "." so the structure is
# created relative to the current working directory.
# (see ?initProject)
initProject(configurationDirectory = ".")

# get paths of all relevant project files
projectConfiguration <-
  ospsuite.reportingframework::createProjectConfiguration(
    path = "ProjectConfiguration.xlsx"
  )

initLogfunction(projectConfiguration)


# 1) Read observedData -------------------------------------------------------
# (see vignette(package = 'ospsuite.reportingframework',topic = 'Data_import_by_dictionary'))

# read data as data.table
dataObserved <- readObservedDataByDictionary(
  projectConfiguration = projectConfiguration
)

# add aggregated  groups of data
dataObserved <- rbind(
  dataObserved,
  aggregateObservedDataGroups(
    dataObserved = dataObserved,
    groups = c("1234_iv", "1234_po")
  ),
  fill = TRUE
)
# for the manually added groups the configuration sheet in Reports.xlsx has to be updated
updateDataGroupId(projectConfiguration, dataObserved)

# 2) Export Populations -------------------------------------------------------
# (see vignette(package = 'ospsuite.reportingframework', topic = 'Population'))

exportVirtualTwinPopulations(
  projectConfiguration = projectConfiguration,
  populationNames = NULL,
  modelFile = "po_3_mg_solution.pkml",
  overwrite = FALSE
)

exportRandomPopulations(
  projectConfiguration = projectConfiguration,
  populationNames = NULL,
  overwrite = FALSE
)


# 3) Simulations ------------------------------------------------------
# (see vignette(package = 'ospsuite.reportingframework', topic = 'Tutorial_Timeprofiles'))
scenarioList <-
  createScenariosWrapped(
    projectConfiguration = projectConfiguration,
    scenarioNames = NULL
  )

scenarioResults <- runAndSaveScenarios(
  projectConfiguration = projectConfiguration,
  scenarioList = scenarioList,
  simulationRunOptions = ospsuite::SimulationRunOptions$new(
    showProgress = TRUE
  )
)

# 4) Create Output Plots -----------------------------------------------------
# (see vignette(package = 'ospsuite.reportingframework', topic = 'Tutorial_Timeprofiles'))

addDefaultConfigForTimeProfilePlots(
  projectConfiguration = projectConfiguration,
  sheetName = "TimeProfiles",
  overwrite = FALSE
)


runPlot(
  nameOfplotFunction = "plotTimeProfiles",
  projectConfiguration = projectConfiguration,
  configTableSheet = "TimeProfiles",
  inputs = list(
    dataObserved = dataObserved,
    scenarioResults = scenarioResults,
    referenceScaleVector = list('1mg iv simulation' = 'grey'),
    xScaleArgs = list(limits = c(NA, NA))
  )
)

# 5) Create Report document --------------------------------------------------
mergeRmds(
  projectConfiguration = projectConfiguration,
  newName = "TutorialPlots",
  title = "Plots generated by tutorial",
  sourceRmds = c("TimeProfiles")
)

renderWord(
  fileName = file.path(projectConfiguration$outputFolder, "TutorialPlots.Rmd")
)

# finalize workflow---------------------
addMessageToLog("finalize workflow")

# save Session Infos including the loaded packages and R version, into a log file
saveSessionInfo()
