#' Function to compare the AUC Ratios of Use Case 2, calculate by individual ratios and ratios of population statistics
#'
#'
#' @param projectConfiguration An object containing the project configuration settings.
#' @param onePlotConfig A data.table containing the configuration for the specific plot to be generated with a unique plotName
#' @param ... Additional arguments that may be passed to custom plotting functions.
#'
#' @return A list of plots and tables generated by the function. Each element in the list should be named with a unique key corresponding to the plot or table.
#'
#'
plotMethodComparison <- function(projectConfiguration,
                           onePlotConfig, ...) {
  # Initialize list of plots and tables
  plotList <- list()

  plotData <- rbind(fread(file.path(projectConfiguration$outputFolder,'PKParameter_Boxplot2','Concentration-ratio.csv')) %>%
                      dplyr::mutate(method = 'statistics of individual ratios'),
                    fread(file.path(projectConfiguration$outputFolder,'PKParameter_Boxplot2_Test','Concentration-ratio.csv')) %>%
                      dplyr::mutate(method ='populations statistics'),
                    fill = TRUE)


  plotObject <- ospsuite.plots::initializePlot()  +
    geom_boxplot(data = plotData,
                 mapping = aes(x = scenario, lower = get('25th percentile'), upper = get('75th percentile'),
                               middle = get('50th percentile'), ymin = get('5th percentile'), ymax = get('95th percentile'),
                               fill = method),
                 stat = "identity") +
    labs(x = '',
         y = 'AUC_inf ratio')


  # Set attributes for the plot export
  plotObject <- setExportAttributes(object = plotObject,
                                    caption =  paste("Comaprison of percentile calculation shown as box-whisker plot, which indicates the",
                         paste(formatPercentiles(c(0.05,0.25,0.5,0.75,0.95),suffix = '',allAsPercentiles = TRUE),collapse = ', '),'percentiles'))
  plotList[['Boxwhisker']] <- plotObject

  plotObject <- ospsuite.plots::initializePlot()  +
    geom_pointrange(
      data = plotData,
      mapping = aes(
        x = scenario,
        y = get("arith mean"),
        ymax = get("arith mean") + get("arith standard deviation"),
        ymin = get("arith mean") - get("arith standard deviation"),
        color = method
      ), position = position_dodge(1)
    ) +
    labs(x = '',
               y = 'AUC_inf ratio')




  # Set attributes for the plot export
  plotObject <- setExportAttributes(object = plotObject,
                                    caption =  'Comparison of arithmetric mean  and standard deviation calculation')
  plotList[['ArithMean']] <- plotObject


  plotObject <- ospsuite.plots::initializePlot()  +
    geom_pointrange(
      data = plotData,
      mapping = aes(
        x = scenario,
        y = get("arith mean"),
        ymax = get("geo mean") * get("geo CV"),
        ymin = get("geo mean") / get("geo CV"),
        color = method
      ), position = position_dodge(1)
    ) +
    labs(x = '',
                y = 'AUC_inf ratio')


  # Set attributes for the plot export
  plotObject <- setExportAttributes(object = plotObject,
                                    caption =  'Comparison of geometric mean and geometric standarddeviation calculation')
  plotList[['GeohMean']] <- plotObject

  # the return value of the function must be the list of plots and tables
  return(plotList)
}


