#' Custom Plot Function Template
#'
#' This template provides a structure for creating custom plot functions that can be used with the `runPlot` function.
#' Users can modify the provided code to generate their own plots and tables based on specific configurations.
#'
#' Users may provide a plot configuration table to define the plots to be generated. However, this is not mandatory.
#' If a configuration table is provided, it must contain the following key columns:
#' - **`Header`**: A descriptive title for the plot section.
#' - **`Level`**: An integer indicating the header level for the plot section.
#' - **`PlotName`**: A identifier for each plot. This is used to specify which plots to generate.
#' It can contain additional columns with any other parameters required for the specific plots.
#'
#' If a configuration table is provided, `runPlot` will call this plot function multiple times, once for each unique `plotName` in the table.
#'
#' Mandatory Input parameters:
#' @param projectConfiguration An object containing the project configuration settings.
#' This includes paths to input files and output directories.
#' @param onePlotConfig A data.table containing the configuration for the specific plot to be generated with a unique plotName
#' Optional input parameter can be defined, the `runPlot` function will pass all parameters of the received by the input variable `inputs`.
#' You can use the ellipsis (...) to pass additional parameter.
#' @param ... Additional arguments that may be passed to custom plotting functions.
#'
#' @return A list of plots and tables generated by the function. Each element in the list should be named with a unique key corresponding to the plot or table.
#'
#' @examples
#'
#' \dontrun{
#' # Example of how to use the custom plot function with runPlot
#' runPlot(
#'   projectConfiguration = projectConfig,
#'   plotFunction = "plotMyFunction",
#'   configTableSheet = "mySheet",  # Optional: Provide a configuration table if desired
#'   inputs = list(additionalParameter1 = 1,
#'   additionalParameter2 = 'bold')
#' )
#' }
#'
plotMyFunction <- function(projectConfiguration,
                           onePlotConfig, ...) {
  # Initialize list of plots and tables
  plotList <- list()

  # Add your own code below; the following are examples of how to add headers, figures, and tables or customize a default function

  # Check if required libraries are loaded
  if (!requireNamespace("tidyr", quietly = TRUE) || !requireNamespace("data.table", quietly = TRUE)) {
    stop("Please install the necessary libraries: tidyr and data.table.")
  }

  # Example: Add a figure
  plotObject <- ospsuite.plots::plotHistogram(
    data = data.frame(x = rnorm(100)),  # Generate random data
    mapping = ggplot2::aes(x = x)        # Define aesthetics
  )

  # Set attributes for the plot export
  plotObject <- setExportAttributes(object = plotObject,
                                    caption =  'This is my plot caption',
                                    footNoteLines = 'These are plot footnotes', # default NULL
                                    exportArguments =   list(width = 12)  # default NULL, additionally arguments passed to ospsuite.plots::exportPlot()
  )
  # Store the plot in the list with a unique key
  plotList[['figureKey']] <- plotObject

  # Example: Add a table
  dt <- data.table(
    x = rnorm(1000),                      # Generate random data
    class = sample(c("Female", "Male"), size = 1000, replace = TRUE)  # Create a categorical variable
  ) %>%
    .[, as.list(quantile(x)), by = "class"]  # Calculate quantiles by class

  # Set attributes for the table export
  dt <- setExportAttributes(object = dt,
                                    caption =  'This is my table caption',
                                    footNoteLines = 'These are table footnotes' # default NULL
  )
  # Store the table in the list with a unique key
  plotList[['tableKey']] <- dt


  # Example: Customize plots of a default function
  plotListNew <- plotTimeProfiles(projectConfiguration = projectConfiguration,
                                  onePlotConfig = onePlotConfig,
                                  ...)

  # adjust one of the plots by adding new ggplot layers
  plotListNew[['myPlotName']] <- plotListNew[['myPlotName']] +
    geom_hline(yintercept = 0)


  # adjust one of the plots by editing the export attributes
  plotListNew[['myPlotName']] <-
    setExportAttributes(object = plotListNew[['myPlotName']],
                        caption =  'That is my customized caption')


  # merge plots
  plotList <- c(plotList,plotListNew)

  # the return value of the function must be the list of plots and tables
  return(plotList)
}
#' Validation Function for Custom Plot Configuration
#'
#' If you use a config Table you can add a validation function.
#' The name of the validation function is constructed by the `nameOfplotFunction` input variable of the function `runPlot`:
#' `nameOfValidationFunction` <- paste0(gsub('^plot', 'validate', `nameOfplotFunction`), 'Config')
#' if a function with this name exist it will be evaluated to check the validity of the config table, otherwise
#' the default function is applied which just check the validity of the columns Level, Header and PlotName.
#' The function should throw errors if the config table is not valid.
#'
#' This function validates the configuration table for the custom plot function.
#' It checks if the necessary columns are present and can be extended for additional checks.
#'
#' @param configTable A data.table containing the configuration for the plot.
#' @param ... Additional arguments for customization.
#'
#' @return invisible NULL if valid, otherwise throws an error.
validateMyFunctionConfig <- function(configTable,...){

  # for customizing of default function, you can use the corresponding validation functions
  validateTimeProfilesConfig(configTable, ...)

  return(invisible())
}
