#' Custom Plot Function Template
#'
#' This template provides a structure for creating custom plot functions that can be used with the `runPlot` function.
#' Users can modify the provided code to generate their own plots and tables based on specific configurations.
#'
#' Users may provide a plot configuration table to define the plots to be generated. However, this is not mandatory.
#' If a configuration table is provided, it should contain the following key columns:
#' - **`header`**: A descriptive title for the plot section.
#' - **`level`**: An integer indicating the header level for the plot section.
#' - **`plotName`**: A identifier for each plot. This is used to specify which plots to generate.
#' - **Additional columns**: Any other parameters required for the specific plots.
#'
#' If a configuration table is provided, `runPlot` will call this plot function multiple times, once for each unique `plotName` in the table.
#'
#' @param projectConfiguration An object containing the project configuration settings.
#' This includes paths to input files and output directories.
#' @param onePlotConfig A data.table containing the configuration for the specific plot to be generated with a uniwue plotName
#' @param ... Additional arguments that may be passed to custom plotting functions.
#'
#' @return A list of plots and tables generated by the function. Each element in the list should be named with a unique key corresponding to the plot or table.
#'
#' @examples
#'
#' \dontrun{
#' # Example of how to use the custom plot function with runPlot
#' runPlot(
#'   projectConfiguration = projectConfig,
#'   plotFunction = myPlotFunction,
#'   subfolder = "custom_plots",
#'   configTableSheet = "PlotConfigurations",  # Optional: Provide a configuration table if desired
#'   inputs = list(additionalParameter1 = 1,
#'   additionalParameter2 = 'bold')
#' )
#' }
#'
myPlotFunction <- function(projectConfiguration,
                           onePlotConfig, ...) {
  # Initialize list of plots and tables
  plotList <- list()

  # Check if all needed libraries are loaded
  require(tidyr)
  require(data.table)

  ## Add your own code below; the following are examples of how to add headers, figures, and tables --------

  # Example: Add a figure
  plotObject <- ospsuite.plots::plotHistogram(
    data = data.frame(x = rnorm(100)),  # Generate random data
    mapping = ggplot2::aes(x = x)        # Define aesthetics
  )

  # Set attributes for the plot
  setattr(plotObject, 'caption', 'This is my plot caption')
  setattr(plotObject, 'footNoteLines', 'These are plot footnotes')
  plotList[['figureKey']] <- plotObject  # Store the plot in the list with a unique key

  # Example: Add a table
  dt <- data.table(
    x = rnorm(1000),                      # Generate random data
    class = sample(c("Female", "Male"), size = 1000, replace = TRUE)  # Create a categorical variable
  ) %>%
    .[, as.list(quantile(x)), by = "class"]  # Calculate quantiles by class

  # Set attributes for the table
  setattr(dt, 'caption', 'This is my table caption')
  setattr(dt, 'footNoteLines', 'These are table footnotes')
  plotList[['tableKey']] <- dt  # Store the table in the list with a unique key

  return(plotList)  # Return the list of plots and tables
}
