#' Run Plot Function
#'
#' This function generates .Rmd files for creating plots based on user-defined configurations.
#' It reads the specified configuration table, evaluates the selected plot function, and manages
#' the output of plots and tables.
#'
#' @param projectConfiguration A ProjectConfiguration object containing the project configuration settings.
#' This should include paths to input files and output directories.
#' @param functionKey A character string that selects the plot function to use.
#' Valid options depend on the available plot functions in your project.
#' If NULL, a plot function must be provided via `plotFunction`.
#' @param plotFunction An optional function to be used for plotting.
#' If provided, this will override the selection made by `functionKey`.
#' @param subfolder A character string specifying the subfolder where results will be saved.
#'  If `functionKey` is used, the default value will be the sheet name of the plot configuration.
#' @param configTableSheet A character string representing the name of the sheet in the "Plots" configuration table from which to read plot configurations.
#' @param suppressExport A logical value indicating whether to suppress the export of the Rmd file.
#'  If TRUE, the function will return the generated plots as a list without creating the Rmd file
#' @param plotNames A character vector of plot names to filter which plots should be generated.
#' If provided, suppressExport is set to TRUE, all plots specified in the configuration will be processed and provided as list, but not exported to the Rmd file.
#' @param inputs A list of additional inputs for the plotting functions. This can include any parameters that the selected plot function requires.
#'
#' @return An invisible list of plots generated by the function. Each element in the list corresponds to a plot created during the execution. If `plotNames` is provided, the Rmd export is suppressed, and only the plot list is returned.
#'
#' @details
#' The `runPlot` function is designed to facilitate the generation of plots based on configurations defined in a specified configuration table. The function will:
#' - Load the configuration table for plots based on the specified sheet name.
#' - Validate the configuration and ensure that all required parameters are provided.
#' - Execute the designated plot function, either selected by `functionKey` or provided directly via `plotFunction`.
#' - Save the generated plots in the specified subfolder.
#' - Handle errors during plot generation, allowing for graceful degradation and warnings instead of halting execution.
#'
#' If the `plotNames` parameter is set, the function will suppress the Rmd export and return a list of plots generated instead.
#' This is useful when you want to generate specific plots without creating an accompanying .Rmd file for fast check in the daily work
#' or to customize plots generated
#'
#' Users can utilize the `openFigureTemplate` function to open a template for creating custom plot functions. This function can be called directly:
#' `openFigureTemplate().` Additionally, the template is available as an RStudio Add-in for easy access.
#'
#' @examples
#'
#' \dontrun{
#' # Run the plot generation function with Rmd export
#' runPlot(
#'   projectConfiguration = projectConfiguration,
#'   functionKey = "plotTimeProfiles",
#'   configTableSheet = "TimeProfiles",
#'   inputs = list(dataObserved = dataObserved,scenarioResults = scenarioResults)
#' )
#'
#' # Run the plot generation function without Rmd export, returning a plot list
#' plotList <- runPlot(
#'   projectConfiguration = projectConfiguration,
#'   functionKey = "plotTimeProfiles",
#'   configTableSheet = "TimeProfiles",
#'   plotNames = c("Plot1", "Plot2"),
#'   inputs = list(dataObserved = dataObserved,scenarioResults = scenarioResults)
#' )
#'
#' # open the template for custom plot functions
#' openFigureTemplate()
#' }
#'
#' @export
runPlot <- function(projectConfiguration,
                    functionKey = NULL,
                    plotFunction = NULL,
                    subfolder = NULL,
                    configTableSheet = NULL,
                    plotNames = NULL,
                    suppressExport = FALSE,
                    inputs = list()) {
  loadConfigTableEnvironment(projectConfiguration)

  suppressExport = suppressExport | !is.null(plotNames)

  # Initialize PlotManager for RMD generation
  rmdPlotManager <- RmdPlotManager$new(
    rmdfolder = file.path(projectConfiguration$outputFolder),
    suppressExport = !getOption('OSPSuite.RF.withPlotExport',default = TRUE) |
      suppressExport
  )
  rmdPlotManager$evaluateFunctionkey(subfolder = subfolder,
                                     functionKey = functionKey,
                                     plotFunction = plotFunction,
                                     configTableSheet = configTableSheet)

  # read configuration table
  configTable <-
    readConfigTableForPlot(sheetName = configTableSheet,
                           validateConfigTableFunction = rmdPlotManager$validateConfigTableFunction,
                           plotNames = plotNames,
                           inputs = inputs)

  if (is.null(configTable)){
    plotList <- do.call(what = rmdPlotManager$validateConfigTableFunction,
                        args = c(list(projectConfiguration = projectConfiguration,
                                      configTable = onePlotConfig),
                                 inputs)
    )
    rmdPlotManager$exportPlotList(plotList)
  } else {
    plotList <- list()
    iRow <- 1
    levelLines <- which(!is.na(configTable$level))
    while (iRow <= nrow(configTable)) {
      if (!is.na(configTable$level[iRow])) {
        # Add section headers
        rmdPlotManager$addHeader(configTable$header[iRow], level = configTable$level[iRow])
        iRow <- iRow + 1
      } else {
        # Execute plot section
        iEndX <- utils::head(which(levelLines > iRow), 1)
        iEnd <- if (length(iEndX) == 0) nrow(configTable) else levelLines[iEndX] - 1

        for (onePlotConfig in split(configTable[seq(iRow, iEnd)], by = "plotName")) {
          tryCatch({
            plotListiRow <- do.call(what = rmdPlotManager$plotFunction,
                                args = c(list(projectConfiguration = projectConfiguration,
                                              onePlotConfig = onePlotConfig),
                                         inputs)
                                )
            rmdPlotManager$dataObserved <- plotListiRow[['dataObservedIndices']]
            plotListiRow[['dataObservedIndices']] <- NULL
            rmdPlotManager$exportPlotList(plotListiRow)
            if (rmdPlotManager$suppressExport) plotList <- c(plotList,plotListiRow)
          }, error = function(err) {
            if (!getOption("OSPSuite.RF.skipFailingPlots", default = FALSE)) {
              stop(err)
            } else {
              warning(paste("Error during creation of:", onePlotConfig$plotName[1], "Message:", conditionMessage(err)))
            }
          })
        }
        iRow <- iEnd + 1
      }
    }
  }

  if (getOption('OSPSuite.RF.withEPackage') &
      (!is.null(rmdPlotManager$configTable))){
    addScenariosToEPackage(projectConfiguration = projectConfiguration,
                           configTable = rmdPlotManager$configTable,subfolder = subfolder)

    if (nrow(rmdPlotManager$dataObserved) > 0 & exists(x = 'dataObserved')){
      exportTimeProfileDataForEPackage(
        projectConfiguration = projectConfiguration,
        dataToExport = merge(rmdPlotManager$dataObserved, dataObserved, by = '.Id')
      )
    }
  }

  # create rmd
  rmdPlotManager$writeRmd()

  return(invisible(plotList))
}
readConfigTableForPlot <- function(sheetName, validateConfigTableFunction,inputs,plotNames){
  if (is.null(sheetName)) return(NULL)

  # read configuration tables
  configTable <- xlsxReadData(
    wb = projectConfiguration$plotsFile,
    sheetName = sheetName,
    skipDescriptionRow = TRUE
  )

  # filter rows with selected plotNames
  if ('plotName' %in% names(configTable) & !is.null(plotNames)){
    checkmate::assertNames(plotNames,subset.of = configTable[!is.na(plotName)]$plotName)
    configTable <- configTable[plotName %in% plotNames]
  }
  # add scenario names
  if ('scenario' %in% names(configTable)){
    configTable <-
      merge(
        configTable,
        configEnv$scenarios[, c('scenarioName', 'longName','shortName','section')],
        by.x = 'scenario',
        by.y = 'scenarioName',
        all.x = TRUE,
        sort = FALSE
      ) %>%
      data.table::setnames(old = c('longName','shortName','section'),
                           c('scenarioLongName','scenarioShortName','scenarioSection'))

    if ('scenarioName' %in% names(configTable)){
      configTable[!is.na(scenarioName) & scenarioName !='',
                  scenarioLongName := scenarioName]
    }
  }

  # validate
  do.call(what = validateConfigTableFunction,
          args = c(list(configTable = configTable),
                   inputs))


  return(configTable)
}

# plotAddons ------------
#' Add Facets to a ggplot Object
#'
#' This function adds facets to a given ggplot object, allowing for better visualization of data subsets.
#' Faceting is done by the variable `plotTag`.
#'
#' @param plotObject A ggplot object to which the facets should be added.
#' @param facetScale A character string indicating the scale of the facets. Options are "free", "fixed", "free_x", or "free_y".
#' @param facetAspectRatio A numeric value specifying the aspect ratio of the facets. Default is 0.5.
#' @param nFacetColumns An integer specifying the number of columns to use for the facet layout. If NULL, no faceting is done.
#'
#' @return An updated ggplot object with facets added.
#' @keywords internal
addFacets <- function(plotObject,
                      facetScale,
                      facetAspectRatio = 0.5,
                      nFacetColumns) {
  # avoid warnings for global variables during check
  plotTag <- NULL

  plotObject <- plotObject +
    ggplot2::theme(aspect.ratio = facetAspectRatio)


  if (!is.null(nFacetColumns)) {
    plotObject <- plotObject +
      ggplot2::facet_wrap(
        facets = ggplot2::vars(plotTag),
        scales = facetScale,
        ncol = nFacetColumns
      ) +
      ggplot2::theme(strip.background = element_rect(fill = NA,color = NA),
                     strip.text = element_text(hjust = 0,vjust = 1))

  }

  return(plotObject)
}


# auxiliaries ----
#' Returns a Scale Vector Usable for Manual Scaling in ggplot
#'
#' @param namesOfScaleVector Names of the vector.
#' @param listOfValues List of possible entries. Takes the first where all values are not NA.
#'
#' @return A scale vector.
#' @keywords internal
getScalevector <- function(namesOfScaleVector,
                           listOfValues) {
  checkmate::assertCharacter(namesOfScaleVector, any.missing = FALSE, min.len = 1, unique = TRUE)
  checkmate::assertList(listOfValues)

  scaleVector <- NULL
  for (values in listOfValues) {
    if (!is.null(values) && !any(is.na(values))) {
      scaleVector <- values
      break
    }
  }

  if (is.null(scaleVector)) {
    stop(paste("no valid values for scalevector for", paste0(namesOfScaleVector, collapse = ", ")))
  }

  names(scaleVector) <- namesOfScaleVector

  return(scaleVector)
}


#' Get Default Colors for Scale Vector
#'
#' This function generates a vector of default colors based on the specified shade and number of colors required.
#' It provides colors from the ggsci package for small numbers and a custom color map for larger requests.
#'
#' @param shade A character string indicating the shade of colors to return.
#'   Must be either "dark" or "light". Default is "dark".
#'
#' @param n An integer specifying the number of colors to return. Must be greater than or equal to 1.
#'
#' @details
#' - For `n` values less than or equal to 10, the function uses the ggsci package's "category20c" palette.
#' - For `n` values greater than 10, it retrieves colors from the predefined color map of the package `ospsuite.plots` named "ospDefault".
#' - If `n` exceeds the maximum number of colors available in "ospDefault", an error is raised.
#'
#' @return A character vector of color values in hexadecimal format.
#'
#' @keywords internal
getDefaultColorsForScaleVector <- function(shade = c("dark", "light"), n) {
  checkmate::assertIntegerish(n, lower = 1, len = 1)
  shade <- match.arg(shade)
  if (n <= 10) {
    colorVector <-
      switch(shade,
             dark = ggsci::pal_d3("category20c")(20)[1:n], # nolint indentation_linter
             light = ggsci::pal_d3("category20c")(20)[(10 + 1):(10 + n)]
      )
  } else {
    if (n > length(ospsuite.plots::colorMaps[["ospDefault"]])) {
      stop(paste("To many colors for colorVector, maximal", length(ospsuite.plots::colorMaps[["ospDefault"]]), "allowed"))
    }
    colorVector <- ospsuite.plots::colorMaps[["ospDefault"]][1:n]
  }

  return(colorVector)
}


#' Get Default Shapes for Scale Vector
#'
#' This function retrieves a vector of default shapes for plotting based on the specified number of shapes required.
#' It utilizes shape settings from the ospsuite.plots package.
#'
#' @param n An integer specifying the number of shapes to return. Must be greater than or equal to 1.
#'
#' @details
#' - The function calls `getOspsuite.plots.option` to obtain the default shape values.
#' - If no shapes are available, an error is raised, prompting the user to set defaults using `ospsuite.plots::setDefaults()`.
#' - If the requested number of shapes exceeds the available shapes, an error is raised.
#'
#' @return A character vector of shape values.
#'
#' @keywords internal
getDefaultShapesForScaleVector <- function(n) {
  shapes <- ospsuite.plots::getOspsuite.plots.option(optionKey = ospsuite.plots::OptionKeys$shapeValues)
  if (is.null(shapes)) {
    stop("no default shape sets for ospsuite.plots. Please use ospsuite.plots::setDefaults()")
  }

  if (n > length(shapes)) {
    stop("not enough shapes available")
  }

  return(shapes[1:n])
}



#' generates named color vectors usable for scale_color_manual
#'
#' @param dt `data.table` with aesthetic and index column
#' @param aesthetic  named `list`, names correspond to aesthetic columns,
#'          entries are either 'dark' or 'light'
#' @param index name of index column
#'
#' @return named list of color vectors
#' @export
generateColorScaleVectors <- function(dt,
                                      aesthetic = list(
                                        color = "dark",
                                        fill = "light"
                                      ),
                                      index = "colorIndex") {
  n <- nrow(dt)
  scaleVectors <- list()
  for (col in names(aesthetic)) {
    for (col2 in c(col, setdiff(names(aesthetic), col))) {
      if (!all(is.na(scaleVectors[[col]]))) {
        scaleVectors[[col]] <- dt[[col2]]
        break
      }
    }

    if (is.null(scaleVectors[[col]])) {
      if (n <= 10) {
        if (aesthetic[[col]] == "dark") {
          scaleVectors[[col]] <- ggsci::pal_d3("category20c")(20)[1:n]
        } else {
          scaleVectors[[col]] <- ggsci::pal_d3("category20c")(20)[(10 + 1):(10 + n)]
        }
      } else {
        scaleVectors[[col]] <- ospsuite.plots::colorMaps[["ospDefault"]][1:n]
      }
    }
    names(scaleVectors[[col]]) <- dt[[index]]
  }
  return(scaleVectors)
}


#' Paste Figure Tags for Captions
#'
#' This function generates a formatted caption text by combining unique captions with associated plot tags.
#' If all captions are the same, it returns that caption. Otherwise, it creates a string that includes
#' the unique captions and their corresponding tags.
#'
#' @param dtCaption A data.table containing the captions and plot tags. It must have at least the following columns:
#'   - `captionColumn`: The column name containing the captions.
#'   - `plotTag`: A column containing the plot tags associated with each caption.
#'
#' @param captionColumn A string specifying the name of the column in `dtCaption` that contains the captions.
#'
#' @param endWithDot A logical value indicating whether to append a period at the end of the caption text. Default is FALSE.
#'
#' @return A character string representing the formatted caption text, which includes the captions and associated plot tags.
#'
pasteFigureTags <- function(dtCaption, captionColumn, endWithDot = FALSE) {
  # avoid warning for global variable
  plotTag <- NULL

  if (dplyr::n_distinct(dtCaption[[captionColumn]]) == 1) {
    captionText <- unique(dtCaption[[captionColumn]])
  } else {
    captionTextVector <- dtCaption[, .(tags = paste0(
      get(captionColumn),
      " (", paste(unique(plotTag), collapse = ", "), ")"
    )),
    by = captionColumn
    ]$tags

    allTags <- dtCaption[, .(tags = paste0(" \\(", paste(unique(plotTag), collapse = ", "), "\\)"))]$tags

    captionTextVector <- gsub(allTags, "", captionTextVector)

    captionText <- concatWithAnd(captionTextVector)

    if (endWithDot & length(trimws(captionText)) > 0) {
      captionText <- paste0(captionText, ".")
    }
  }

  return(captionText)
}

#' Concatenate Text Vector with Commas and "and"
#'
#' This function takes a vector of text strings and concatenates them into a single string.
#' For vectors with more than two elements, it separates them with commas and uses "and"
#' before the last element.
#'
#' @param textVector A character vector of text strings to be concatenated.
#' @return A single character string representing the concatenated text.
#'
#' @keywords internal
concatWithAnd <- function(textVector) {

  textVector <- trimws(textVector)
  textVector <- textVector[textVector != '']

  n <- length(textVector)

  if (n == 0) {
    return("")
  } else if (n == 1) {
    return(textVector)
  } else if (n == 2) {
    return(paste(textVector, collapse = " and "))
  } else {
    return(concatWithAnd(c(paste(textVector[1:(n - 1)], collapse = ", "), tail(textVector, 1))))
  }
}


' Process Percentiles
#'
#' This function takes a numeric vector of percentiles and maps specific values to their corresponding labels.
#' It also formats other numeric values based on whether they are integers or not.
#'
#' @param percentiles A numeric vector of percentiles (0, 50, 100, and other values).
#' @param suffix A character string to append to formatted percentile values.
#'
#' @return A vector containing the mapped labels for specific percentiles and formatted strings for others.
formatPercentiles <- function(percentiles,suffix = '',allAsPercentiles = FALSE){

  lapply(percentiles*100, function(p) {
    if (p == 0 & !allAsPercentiles){
      'min'
    } else if (p == 50 & !allAsPercentiles){
      'median'
    } else if (p == 100 & !allAsPercentiles){
      'max'
    } else if (p %% 1 == 0) {
      paste0(scales::label_ordinal()(x = p), suffix)
    } else {
      paste0(p, 'th', suffix)
    }

  }) %>% unlist()
}

#' Generate a Plot Tag
#'
#' This function generates a plot tag based on the provided index.
#' The function takes an index and returns the corresponding letter
#' from the alphabet in uppercase.
#'
#' @param index An integer representing the position in the alphabet
#'
#' @return A character string representing the uppercase letter
#' corresponding to the given index.
#' @keywords internal
generatePlotTag <- function(index){
  toupper(letters[index])
}

#' Get Y-axis Limits for Plotting
#'
#' This function retrieves the y-axis limits from a given plot configuration
#' based on the specified y-axis scale (linear or logarithmic). It also allows
#' for additional arguments to be passed for further customization.
#'
#' @param onePlotConfig A list containing the plot configuration, which must
#' include `ylimit_linear` and `ylimit_log` elements if direction is `y` otherwise
#' `xlimit_linear` and `xlimit_log`
#'
#' @param xOryScale A character string indicating the type of scale to use for the
#' y(x)-axis. It should be either "linear" or "log".
#'
#' @param direction A character string indicating direction of the axis must be `x` or `y`
#' default is `y`.
#'
#' @param ... Additional arguments that can be passed to customize the y-scale.
#' These can include `yscale.args` for further customization of the y-axis scale.
#'
#' @return A list of y-scale arguments, including limits, which can be used
#' in plotting functions.
#' @keywords internal
getXorYlimits <- function(onePlotConfig,xOryScale,direction = c('y','x'),...){

  direction <-match.arg(direction)

  dotargs = list(...)
  if ( paste0(direction,'scale.args') %in% dotargs) {
    xOrYscale.args = dotargs[[paste0(direction,'scale.args')]]
  } else {
    xOrYscale.args = list()
  }

  if (tolower(xOryScale) == 'linear'){
    scaleTxt <- onePlotConfig[[paste0(direction,'limit_linear')]][1]
  } else {
    scaleTxt <- onePlotConfig[[paste0(direction,'limit_log')]][1]
  }
  if (!is.null(scaleTxt) && !is.na(scaleTxt)){
    xOrYscale.args <- modifyList(xOrYscale.args,
    list(limits = eval(parse(text = scaleTxt))))
  }

  return(xOrYscale.args)

}



# validation ----------------
#' Validate Configuration Table for Plots
#'
#' This function validates the structure and content of the configuration table for plots.
#'
#' @param configTable A data.table containing the plot configuration to be validated.
#' @return NULL. The function will throw an error if the validation fails.
#' @keywords internal
validateConfigTableForPlots <- function(configTable){
  configTablePlots <- validateHeaders(configTable)
  validateOutputIdsForPlot()
  validateDataGroupIdsForPlot()

  return()
}

#' checks if config table header and plot rows are strict separated
#'
#' @param configTable `data.table` configuration table to check
#'
#' @return configuration table without header lines
#' @export
validateHeaders <- function(configTable) {
  # avoid warning for global variable
  level <- NULL

  configTableHeader <- configTable[!is.na(level)]
  checkmate::assertIntegerish(configTableHeader$level, lower = 1, any.missing = FALSE)
  checkmate::assertCharacter(configTableHeader$header, any.missing = FALSE)

  if (any(!is.na(configTableHeader %>% dplyr::select(setdiff(
    names(configTableHeader), c("level", "header")
  ))))) {
    stop(
      "Invalid plot configuration table. For Rows with headers all other columns must be empty."
    )
  }

  configTablePlots <- configTable[is.na(level)]
  if (!all(configTablePlots[,
                            lapply(.SD, function(x)
                              all(is.na(x))),   # nolint indentation_linter
                            .SDcols = "header"])) {
    stop("Invalid plot configuration table. Missing header for level")
  }

  return(configTablePlots)
}

#' validate types of plot configuration tables
#'
#' @template configTablePlots
#' @param charactersWithoutMissing vector with character columns, where no missing value is allowed
#' @param charactersWithMissing  vector with character column, where values may missing
#' @param numericColumns  vector with numeric columns
#' @param logicalColumns vector with booleans
#' @param numericRangeColumns vector with columns where entries must be evaluate to a numeric of length 2
#' @param subsetList  list where each entry is a list:
#'  list(cols = 'vector with columns',
#'  allowedValues = vector with allowed values)
#'
validateConfigTablePlots <- function(configTablePlots,
                                     charactersWithoutMissing = NULL,
                                     charactersWithMissing = NULL,
                                     numericColumns = NULL,
                                     logicalColumns = NULL,
                                     numericRangeColumns = NULL,
                                     subsetList = list()) {

  # Validate character columns
  if (!is.null(charactersWithoutMissing)) {
    invisible(lapply(charactersWithoutMissing, function(col) validateColumn(col, configTablePlots, "character", FALSE)))
  }

  if (!is.null(charactersWithMissing)) {
    invisible(lapply(charactersWithMissing, function(col) validateColumn(col, configTablePlots, "character", TRUE)))
  }

  # Validate numeric columns
  if (!is.null(numericColumns)) {
    invisible(lapply(numericColumns, function(col) validateColumn(col, configTablePlots, "numeric")))
  }

  # Validate logical columns
  if (!is.null(logicalColumns)) {
    invisible(lapply(logicalColumns, function(col) validateColumn(col, configTablePlots, "logical")))
  }

  # Validate subset list
  checkmate::assertList(subsetList, types = "list")
  validateSubsetList(subsetList, configTablePlots)

  if (!is.null(numericRangeColumns)) {
    validateNumericRangeColumns(numericRangeColumns, configTablePlots)
  }

  return(invisible())
}

#' validate a Column
#'
#' This function validates a specified column in a data frame based on the
#' provided type. It checks for character, numeric, or logical types and
#' can enforce the presence or absence of missing values.
#'
#' @param col A string representing the name of the column to validate.
#' @param data A data frame containing the column to be validated.
#' @param type A string specifying the type of validation to perform.
#'             Options are "character", "numeric", or "logical".
#' @param anyMissing A logical value indicating whether missing values are allowed.
#'                   Default is FALSE.
#'
#' @return NULL. The function will throw an error if the validation fails.
#' @keywords internal
validateColumn <- function(col, data, type, anyMissing = FALSE) {
  switch(
    type,
    character = checkmate::assertCharacter(
      data[[col]],
      any.missing = anyMissing,
      .var.name = paste("Plot configuration column", col)
    ),
    numeric = checkmate::assertNumeric(data[[col]], .var.name = paste("Plot configuration column", col)),
    logical = checkmate::assertLogical(
      as.logical(data[[col]]),
      any.missing = FALSE,
      .var.name = paste("Plot configuration column", col)
    )
  )
}


#' validate Subset List
#'
#' Validates the subset list against the provided data frame.
#'
#' @param subsetList A list containing subsets to validate.
#' @param data A data frame containing the columns to validate.
validateSubsetList <- function(subsetList, data) {
  for (subsetCheck in subsetList) {
    checkmate::assertList(subsetCheck, types = c("character", "factor"), names = "named")
    checkmate::assertNames(names(subsetCheck), permutation.of = c("cols", "allowedValues"))
    invisible(lapply(subsetCheck$cols, function(col) {
      if (any(!is.na(data[[col]]))) {
        checkmate::assertNames(
          gsub("[()]", "", splitInputs(data[!is.na(get(col))][[col]])),
          subset.of = subsetCheck$allowedValues,
          .var.name = paste("Plot configuration column", col)
        )
      }
    }))
  }
}



#' validate Numeric Range Columns
#'
#' Validates numeric range columns in the provided data frame.
#'
#' @param columns A vector of column names to validate.
#' @param data A data frame containing the columns to validate.
validateNumericRangeColumns <- function(columns, data) {
  for (col in columns) {
    if (any(!is.na(data[[col]]))) {
      x <- data[!is.na(get(col)), ][[col]]
      if (length(x) > 0) {
        valid <- is.numeric(eval(parse(text = x))) && length(eval(parse(text = x))) == 2
        if (!valid) {
          stop(paste("Invalid inputs in plot configuration column", col))
        }
      }
    }
  }
}


#' Validate Consistency of Values Within Groups
#'
#' This function checks whether specified columns in a data table have consistent values
#' within groups defined by one or more grouping columns. If any column contains more than
#' one unique value within a group, an error is raised.
#'
#' @param dt A data.table or data.frame containing the data to be validated.
#' @param valueColumns A character vector of column names to check for consistency.
#' @param groupingColumns A character vector of column names that define the groups.
#'        Default is 'plotName'.
#'
#' @return Returns NULL (invisible) if all checks pass. Raises an error if any value
#'         column contains inconsistent values within a group.
#'
#' @export
validateGroupConsistency <- function(
    dt,
    valueColumns,
    groupingColumns = 'plotName') {

  # Check for unique values of value columns for each group defined by groupingColumns
  uniqueValueCounts <-
    dt[, lapply(.SD, function(x) {
      length(unique(x))
    }), by = groupingColumns,
    .SDcols = valueColumns]

  # Check if any value column has more than one unique value within each group
  lapply(valueColumns, function(col) {
    if (any(uniqueValueCounts[[col]] > 1)) {
      stop(paste("Values for", col, "should be the same within each group defined by", paste(groupingColumns, collapse = ", ")))
    }
  })

  return(invisible())
}


#' check if at least one of the following columns is selected
#'
#' @template configTablePlots
#' @param columnVector vector of columns to check
#'
validateAtleastOneEntry <- function(configTablePlots, columnVector) {
  if (nrow(configTablePlots[rowSums(is.na(configTablePlots)) == length(columnVector), ]) > 0) {
    stop(paste(
      "Invalid configTable, each plot row needs at least one entry in one of the columns",
      paste(columnVector, collapse = ", ")
    ))
  }

  return(invisible())
}


#' Validation of data.table with outputPath Ids
#'
#' @param dtOutputPaths data.table with outputPath Ids
validateOutputIdsForPlot <- function() {
  # avoid warning for global variable
  outputPathId <- NULL

  checkmate::assertFactor(configEnv$outputPaths$outputPathId, any.missing = FALSE,
                          .var.name = 'Outputs column outputPathId')
  checkmate::assertCharacter(configEnv$outputPaths$outputPath, any.missing = FALSE,
                             .var.name = 'Outputs column outputPath')
  checkmate::assertCharacter(configEnv$outputPaths$displayNameOutputs, any.missing = FALSE,
                             .var.name = 'Outputs column displayName')

  if (any(!is.na(configEnv$outputPaths$color))) {
    checkmate::assertCharacter(configEnv$outputPaths$color, any.missing = FALSE,
                               .var.name = 'Outputs column color')
  }

  # Check for unique values for outputpathids
  uniqueColumns <- c("displayNameOutputs", "displayUnit")
  uniqueIDValues <-
    configEnv$outputPaths[, lapply(.SD, function(x) {
      length(unique(x))
    }), by = outputPathId, .SDcols = uniqueColumns]
  tmp <- lapply(uniqueColumns, function(col) { # nolint object_usage
    if (any(uniqueIDValues[[col]] > 1)) stop(paste("values for", col, "should be the same within outputPathId"))
  })

  # check validity of units
  invisible(lapply(
    unique(configEnv$outputPaths$displayUnit),
    function(unit) {
      tryCatch(
        {
          suppressMessages(ospsuite::getDimensionForUnit(unit))
        },
        error = function(e) {
          stop(paste0('Please check sheet Outputs in plotconfiguration file. Unit "', unit, '" is not valid'))
        }
      )
    }
  ))

  return(invisible())
}

#' Validation of data.table with outputPath Ids
#'
#' @param projectConfiguration ProjectConfiguration object
validateDataGroupIdsForPlot <- function() {
  # avoid warning for global variable
  outputPathId <- NULL

  checkmate::assertFactor(
    configEnv$dataGroupIds$group,
    any.missing = FALSE,
    unique = TRUE,
    .var.name = 'DataGroups column group'
  )
  checkmate::assertCharacter(configEnv$dataGroupIds$displayNameData,
                             any.missing = FALSE,
                             .var.name = 'DataGroups column displayName')

  if (any(!is.na(configEnv$dataGroupIds$color))) {
    checkmate::assertCharacter(dtOutputPaths$color, any.missing = FALSE,
                               .var.name = 'DataGroups column color')
  }

  return(invisible())
}

#' Validate Color Vector
#'
#' This function checks if the provided color vector meets the following criteria:
#' - It has a length of 2.
#' - It is named.
#' - All values are either NA or valid color names.
#'
#' @param colorVector A character vector of colors, which should have a length of 2.
#'
#' @return Returns `invisible()` if the checks pass.
#'
#' @throws An error if any of the checks fail.
#' @keywords internal
validateColorVector <- function(colorVector) {
  # Check if the length is 2
  checkmate::assertVector(colorVector, len = 2,any.missing = TRUE,names = 'named')

  # Check if all values are either NA or valid colors
  validColors <- sapply(colorVector, function(x) is.na(x) || isTRUE(grDevices::col2rgb(x, alpha = TRUE)[1] >= 0))

  if (!all(validColors)) {
    stop("All values in colorVector must be either NA or valid color names.")
  }

  return(invisible())
}
